[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  # Make sure these are properly formatted without ${} syntax in the netlify.toml
  # Netlify will substitute the actual environment variables automatically
  VITE_AIRTABLE_API_KEY 
  VITE_AIRTABLE_BASE_ID 
  VITE_AIRTABLE_TABLE_NAME
  VITE_RESEND_API_KEY
  VITE_SUPABASE_EMAIL
  VITE_SUPABASE_KEY
  VITE_SUPABASE_PASSWORD
  VITE_SUPABASE_URL

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
