[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://api.resend.com/:splat"
  status = 200
  force = true
  headers = {Authorization = "Bearer :VITE_RESEND_API_KEY"}

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[redirects]]
status = 200  to = "/index.html"  from = "/*"
